Moved test to front so pytest can test functions. Some tests failed.
====================================================================== FAILURES =======================================================================
________________________________________________________________ test_basic_quickSort _________________________________________________________________

unsortedEvents = [Event(4, Stars & Stares, 2026-03-06, 22:00, Flagstaff), Event(2, Bites & Beers, 2026-03-06, 16:30, Avery), Event(0, B...Event(3, Play & Pals, 2026-03-06, 18:30, Mary Rippon Outdoor Theatre), Event(1, Lunch & Learn, 2026-03-06, 11:30, UMC)]
sortedOrder = [Event(0, Brunch Buddies, 2026-03-06, 09:00, C4C), Event(1, Lunch & Learn, 2026-03-06, 11:30, UMC), Event(2, Bites & B..., Play & Pals, 2026-03-06, 18:30, Mary Rippon Outdoor Theatre), Event(4, Stars & Stares, 2026-03-06, 22:00, Flagstaff)]

    def test_basic_quickSort(unsortedEvents, sortedOrder):
        # TESTING IF quickSort CORRECTLY ORDERS EVENTS BY DATE > TIME > LOCATION
        result = quickSort(unsortedEvents)
>       assert result == sortedOrder
E       assert [Event(0, Bru...Theatre), ...] == [Event(0, Bru...0, Flagstaff)]
E         
E         At index 2 diff: Event(1, Lunch & Learn, 2026-03-06, 11:30, UMC) != Event(2, Bites & Beers, 2026-03-06, 16:30, Avery)
E         Left contains 2 more items, first extra item: Event(3, Play & Pals, 2026-03-06, 18:30, Mary Rippon Outdoor Theatre)
E         Use -v to get more diff

sorting_test.py:107: AssertionError
________________________________________________________________ test_sorted_quickSort ________________________________________________________________

alreadySorted = [Event(0, Brunch Buddies, 2026-03-06, 09:00, C4C), Event(1, Lunch & Learn, 2026-03-06, 11:30, UMC), Event(2, Bites & B..., Play & Pals, 2026-03-06, 18:30, Mary Rippon Outdoor Theatre), Event(4, Stars & Stares, 2026-03-06, 22:00, Flagstaff)]
sortedOrder = [Event(0, Brunch Buddies, 2026-03-06, 09:00, C4C), Event(1, Lunch & Learn, 2026-03-06, 11:30, UMC), Event(2, Bites & B..., Play & Pals, 2026-03-06, 18:30, Mary Rippon Outdoor Theatre), Event(4, Stars & Stares, 2026-03-06, 22:00, Flagstaff)]

    def test_sorted_quickSort(alreadySorted, sortedOrder):
        # TESTING IF quickSort BREAKS/CORRUPTS A SORTED LIST
        result = quickSort(alreadySorted)
>       assert result == sortedOrder
E       assert [Event(0, Bru...Theatre), ...] == [Event(0, Bru...0, Flagstaff)]
E         
E         At index 1 diff: Event(0, Brunch Buddies, 2026-03-06, 09:00, C4C) != Event(1, Lunch & Learn, 2026-03-06, 11:30, UMC)
E         Left contains 3 more items, first extra item: Event(3, Play & Pals, 2026-03-06, 18:30, Mary Rippon Outdoor Theatre)
E         Use -v to get more diff

sorting_test.py:118: AssertionError
______________________________________________________________ test_integrity_quickSort _______________________________________________________________

unsortedEvents = [Event(4, Stars & Stares, 2026-03-06, 22:00, Flagstaff), Event(2, Bites & Beers, 2026-03-06, 16:30, Avery), Event(0, B...Event(3, Play & Pals, 2026-03-06, 18:30, Mary Rippon Outdoor Theatre), Event(1, Lunch & Learn, 2026-03-06, 11:30, UMC)]

    def test_integrity_quickSort(unsortedEvents):
        # TESTING IF quickSort KEEPS DATA INTEGRITY (NO DELETED OR DUPLICATED EVENTS)
        result = quickSort(unsortedEvents)
>       assert len(result) == len(unsortedEvents)
E       assert 9 == 5
E        +  where 9 = len([Event(0, Brunch Buddies, 2026-03-06, 09:00, C4C), Event(0, Brunch Buddies, 2026-03-06, 09:00, C4C), Event(1, Lunch & ..., Bites & Beers, 2026-03-06, 16:30, Avery), Event(3, Play & Pals, 2026-03-06, 18:30, Mary Rippon Outdoor Theatre), ...])
E        +  and   5 = len([Event(4, Stars & Stares, 2026-03-06, 22:00, Flagstaff), Event(2, Bites & Beers, 2026-03-06, 16:30, Avery), Event(0, B...Event(3, Play & Pals, 2026-03-06, 18:30, Mary Rippon Outdoor Theatre), Event(1, Lunch & Learn, 2026-03-06, 11:30, UMC)])

sorting_test.py:129: AssertionError
_____________________________________________________________________ test_agree ______________________________________________________________________

unsortedEvents = [Event(4, Stars & Stares, 2026-03-06, 22:00, Flagstaff), Event(2, Bites & Beers, 2026-03-06, 16:30, Avery), Event(0, B...Event(3, Play & Pals, 2026-03-06, 18:30, Mary Rippon Outdoor Theatre), Event(1, Lunch & Learn, 2026-03-06, 11:30, UMC)]

    def test_agree(unsortedEvents):
        import copy
        result_insert = insertSort(copy.copy(unsortedEvents))
        result_merge  = mergeSort(copy.copy(unsortedEvents))
        result_quick  = quickSort(copy.copy(unsortedEvents))
        assert result_insert == result_merge
>       assert result_merge  == result_quick
E       assert [Event(0, Bru...0, Flagstaff)] == [Event(0, Bru...Theatre), ...]
E         
E         At index 2 diff: Event(2, Bites & Beers, 2026-03-06, 16:30, Avery) != Event(1, Lunch & Learn, 2026-03-06, 11:30, UMC)
E         Right contains 3 more items, first extra item: Event(3, Play & Pals, 2026-03-06, 18:30, Mary Rippon Outdoor Theatre)
E         Use -v to get more diff

sorting_test.py:142: AssertionError
=============================================================== short test summary info ===============================================================
FAILED sorting_test.py::test_basic_quickSort - assert [Event(0, Bru...Theatre), ...] == [Event(0, Bru...0, Flagstaff)]
FAILED sorting_test.py::test_sorted_quickSort - assert [Event(0, Bru...Theatre), ...] == [Event(0, Bru...0, Flagstaff)]
FAILED sorting_test.py::test_integrity_quickSort - assert 9 == 5
FAILED sorting_test.py::test_agree - assert [Event(0, Bru...0, Flagstaff)] == [Event(0, Bru...Theatre), ...]
============================================================ 4 failed, 12 passed in 0.04s =============================================================